<?php 

	/* Template Name: home-studio */ 
?>
<div class="container">
   	<div class="row">
   		<div class="visible-xs"><?php include(locate_template('dotted-line.svg')); ?></div>
   		<h2 class="visible-xs post-title">Le Studio</h2>
   		<div class="visible-xs"><?php include(locate_template('dotted-line.svg')); ?></div>

   		<div class= "carousel-container col-md-offset-1 col-sm-offset-0 col-md-10 col-sm-12">
			<div id="carousel-studio" class="carousel slide text-center" data-ride="carousel">
			  <!-- Wrapper for slides -->
			  <div class="carousel-inner" role="listbox">
			  <!--- html generated by custom javascript	file -->
			 </div>

			  <!-- Controls -->
			  <a class="hidden-xs left carousel-control" href="#carousel-studio" role="button" data-slide="prev">
			    <i class="fa fa-chevron-left fa-4x" aria-hidden="true"></i>
			    <span class="sr-only">Previous</span>
			  </a>
			  <a class="hidden-xs right carousel-control" href="#carousel-studio" role="button" data-slide="next">
			    <i class="fa fa-chevron-right fa-4x" aria-hidden="true"></i>
			    <span class="sr-only">Next</span>
			  </a>

			   <a class="visible-xs left carousel-control" href="#carousel-studio" role="button" data-slide="prev">
			    <i class="fa fa-chevron-left fa-2x" aria-hidden="true"></i>
			    <span class="sr-only">Previous</span>
			  </a>
			  <a class="visible-xs right carousel-control" href="#carousel-studio" role="button" data-slide="next">
			    <i class="fa fa-chevron-right fa-2x" aria-hidden="true"></i>
			    <span class="sr-only">Next</span>
			  </a>
			</div>
		</div>
	</div>
</div>
